#!/usr/bin/env python
"""Exhaustively cross-check the two exact SAT formulations through K=4.

This is a deliberately slow scientific validation script, not part of the
runtime algorithm. It enumerates every distinct basis matrix, retains every
post-two-column-check case, and compares:

1. the Boolean-factorization CNF;
2. the former response-profile CNF; and
3. an independent row-generation oracle that enumerates H directly.

Run from the package directory with::

    python tools/validate_factorization_sat.py
"""

from __future__ import annotations

from itertools import product
import time

import numpy as np

from idQ.basis import reduce_to_basis
from idQ.core import first_three_column_violation, first_two_column_violation
from idQ.sat import (
    build_factorization_sat_instance,
    build_profile_sat_instance,
)
from idQ.utils import (
    is_valid_factorization_counterexample,
    lex_sort_columns,
)


EXPECTED_COUNTS = {
    1: (2, 1),
    2: (7, 1),
    # These post-pair counts include the identity basis.  The main algorithm
    # returns at its earlier identity-submatrix branch, but retaining it here
    # gives the factorization theorem one additional boundary-case check.
    3: (61, 8),
    4: (2480, 545),
}


def dpll(clauses, assignment=None):
    """Small dependency-free DPLL solver used only for validation."""
    assignment = {} if assignment is None else dict(assignment)
    clauses = [tuple(clause) for clause in clauses]

    while True:
        reduced = []
        units = []
        for clause in clauses:
            pending = []
            satisfied = False
            for literal in clause:
                variable = abs(literal)
                if variable in assignment:
                    if assignment[variable] == (literal > 0):
                        satisfied = True
                        break
                else:
                    pending.append(literal)
            if satisfied:
                continue
            if not pending:
                return None
            if len(pending) == 1:
                units.append(pending[0])
            reduced.append(tuple(pending))
        if not reduced:
            return assignment

        changed = False
        for literal in units:
            variable = abs(literal)
            value = literal > 0
            if variable in assignment and assignment[variable] != value:
                return None
            if variable not in assignment:
                assignment[variable] = value
                changed = True
        if changed:
            clauses = reduced
            continue

        signs = {}
        for clause in reduced:
            for literal in clause:
                signs.setdefault(abs(literal), set()).add(literal > 0)
        pure = next(
            (
                (variable, next(iter(values)))
                for variable, values in signs.items()
                if len(values) == 1
            ),
            None,
        )
        if pure is not None:
            assignment[pure[0]] = pure[1]
            clauses = reduced
            continue
        clauses = reduced
        break

    literal = min(clauses, key=len)[0]
    variable = abs(literal)
    for value in (literal > 0, literal < 0):
        solution = dpll(clauses, {**assignment, variable: value})
        if solution is not None:
            return solution
    return None


def enumerate_bases(K):
    """Return every distinct basis obtainable from nonzero K-bit rows."""
    patterns = [
        row for row in product((0, 1), repeat=K)
        if any(row)
    ]
    bases = {(): np.empty((0, K), dtype=int)}
    for subset_code in range(1, 1 << len(patterns)):
        rows = [
            patterns[index]
            for index in range(len(patterns))
            if subset_code & (1 << index)
        ]
        basis = reduce_to_basis(np.asarray(rows, dtype=int)).basis
        key = tuple(tuple(int(value) for value in row) for row in basis)
        bases.setdefault(key, basis)
    return list(bases.values())


def generator_cover_masks(K):
    """Return row-pattern sets generated by admissible non-permutation H."""
    covers = set()
    for values in product((0, 1), repeat=K * K):
        H = np.asarray(values, dtype=int).reshape(K, K)
        if np.any(H.sum(axis=0) == 0) or int(H.sum()) < K + 1:
            continue

        generated = 0
        for x_values in product((0, 1), repeat=K):
            if not any(x_values):
                continue
            output = (np.asarray(x_values, dtype=int) @ H > 0).astype(int)
            output_code = sum(int(output[k]) << k for k in range(K))
            generated |= 1 << output_code
        covers.add(generated)
    return tuple(covers)


def required_row_mask(Q):
    mask = 0
    for row in Q:
        code = sum(int(row[k]) << k for k in range(Q.shape[1]))
        mask |= 1 << code
    return mask


def decode(variables, model):
    return np.asarray(
        [
            [int(variable in model and model[variable]) for variable in row]
            for row in variables
        ],
        dtype=int,
    )


def main():
    start = time.perf_counter()
    total_post_pair = 0
    total_triple_fail = 0
    total_sat = 0

    for K in range(1, 5):
        bases = enumerate_bases(K)
        covers = generator_cover_masks(K)
        post_pair = [
            Q for Q in bases
            if Q.shape[0] > 0 and first_two_column_violation(Q) is None
        ]
        expected_total, expected_post_pair = EXPECTED_COUNTS[K]
        assert len(bases) == expected_total, (K, len(bases))
        assert len(post_pair) == expected_post_pair, (K, len(post_pair))

        k_sat = 0
        k_triple_fail = 0
        for Q in post_pair:
            if first_three_column_violation(Q) is not None:
                k_triple_fail += 1

            required = required_row_mask(Q)
            oracle_sat = any(required & ~cover == 0 for cover in covers)

            factor_encoding = build_factorization_sat_instance(Q)
            factor_model = dpll(factor_encoding.clauses)
            factor_sat = factor_model is not None

            Q_sorted, _ = lex_sort_columns(Q)
            profile_encoding = build_profile_sat_instance(Q_sorted)
            profile_sat = dpll(profile_encoding.clauses) is not None

            assert factor_sat == oracle_sat, ("factor", K, Q.tolist())
            assert profile_sat == oracle_sat, ("profile", K, Q.tolist())

            if factor_model is not None:
                Q_bar = decode(
                    factor_encoding.decision_variables,
                    factor_model,
                )
                H = decode(factor_encoding.factor_variables, factor_model)
                assert is_valid_factorization_counterexample(Q, Q_bar, H), (
                    K,
                    Q.tolist(),
                    Q_bar.tolist(),
                    H.tolist(),
                )
                k_sat += 1

        total_post_pair += len(post_pair)
        total_triple_fail += k_triple_fail
        total_sat += k_sat
        print(
            f"K={K}: bases={len(bases)}, post_pair={len(post_pair)}, "
            f"triple_fail={k_triple_fail}, factor_sat={k_sat}"
        )

    elapsed = time.perf_counter() - start
    print(
        f"Validated {total_post_pair} post-pair bases with zero disagreements; "
        f"triple_fail={total_triple_fail}, factor_sat={total_sat}, "
        f"elapsed={elapsed:.3f}s"
    )


if __name__ == "__main__":
    main()
